### PR TITLE
SIM-26: Added integration test editTest, set order to 5

### PR DESCRIPTION
**Pull request by TSSoftware-hub**

### CODE REVIEW

**Comment by TSSoftware-hub** [comment]
Sergey,

Please review. Thank you.

**Comment by TSSoftware-hub** [comment]
I’m testing update of the record, not creating a new one. My test is 5, are you talking about this?

**Comment by SergeiDemyanenko** [comment]
> 
> 
> I’m testing update of the record, not creating a new one. My test is 5, are you talking about this?

В этом классе нужно тестить вот это /api/edit посмотри как сделан тест на добавление записи.

**Comment by TSSoftware-hub** [comment]
Ok, I will change that

**Pull request merged**
